# Generated by Django 5.1.7 on 2025-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user_confirmpassword_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ConfirmPassword',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=150),
        ),
    ]
