# Generated by Django 5.1.7 on 2025-03-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_user_confirmpassword_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ConfirmPassword',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
