# Generated by Django 5.1.7 on 2025-03-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_confirmpassword_user_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
