# Generated by Django 5.1.7 on 2025-03-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
    ]
